# Generated by Django 3.0.4 on 2021-05-20 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='picuture',
            new_name='picture',
        ),
    ]
